language: node_js
node_js: node

before_deploy:
  - 'npm run build'
  - 'git add -f build'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master